// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf71k9IPQ4aZLngMrLA7WEJCgyVur0QD8',
    appId: '1:569269422358:web:6c2c04202516d08437a837',
    messagingSenderId: '569269422358',
    projectId: 'precinho1',
    authDomain: 'precinho1.firebaseapp.com',
    storageBucket: 'precinho1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbGSeTPML7d2dkmrZkRZiVySid47_38eA',
    appId: '1:569269422358:android:a6141f18c8acba0b37a837',
    messagingSenderId: '569269422358',
    projectId: 'precinho1',
    storageBucket: 'precinho1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-3-ca5-hfNQNfvZuGD6vZhP9GqpnOsAw',
    appId: '1:569269422358:ios:7631f832afbc071737a837',
    messagingSenderId: '569269422358',
    projectId: 'precinho1',
    storageBucket: 'precinho1.appspot.com',
    iosBundleId: 'com.example.sprint2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-3-ca5-hfNQNfvZuGD6vZhP9GqpnOsAw',
    appId: '1:569269422358:ios:7631f832afbc071737a837',
    messagingSenderId: '569269422358',
    projectId: 'precinho1',
    storageBucket: 'precinho1.appspot.com',
    iosBundleId: 'com.example.sprint2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf71k9IPQ4aZLngMrLA7WEJCgyVur0QD8',
    appId: '1:569269422358:web:f94e924c70632b7537a837',
    messagingSenderId: '569269422358',
    projectId: 'precinho1',
    authDomain: 'precinho1.firebaseapp.com',
    storageBucket: 'precinho1.appspot.com',
  );

}